# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

url: 'http://0.0.0.0:4000'
baseurl: ""

filesurl: 'http://0.0.0.0:4000/files'
urlimg: 'http://0.0.0.0:4000/images/'

sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded

# Disable when not in production
google_analytics_tracking_id:
